# TESTING - Docker Composer components
# PROJECT CODE - 53
#
# Docker composer automatically creates a network. The container host matches the container name.
#
# This is the integration set of services so there is no application server, just the mock services.configs:
#
# SERVICES:
# The dockers created by this file are the next services:
# 5310 - [apisimulator-esi-oauth] esi-oauth api simulator service
# 5320 - [apisimulator-esi-data] esi eve online data server api simulator service

version: '3.8'
services:
  apisimulator-esi-oauth:
    container_name: apisimulator-esi-oauth
    image: apimastery/apisimulator
    ports:
      - "5310:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - ../esioauth-simulation:/esioauth-simulation
    command: "bin/apisimulator start /esioauth-simulation -p 6090"

  apisimulator-esi-data:
    container_name: apisimulator-esi-data
    image: apimastery/apisimulator
    ports:
      - "5320:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - ../esidata-simulation:/esidata-simulation
    command: "bin/apisimulator start /esidata-simulation -p 6090"
