# - C I R C L E C I   C O N T I N U O U S   I N T E G R A T I O N
# Download, compile, test and deploy to the production server at Heroku.
# CircleCI has the ability to deploy to Heroku and integrate more than one
#   project on the same pipeline.
# 
# BRANCHES:
#   Experimental: This branch is used to add code that should be confirmed and tested it is operational before going to development.
#                 Usually this is when some changes break the API or are disruptive with previous running code.
#                 The only actions are to compile the source code.
#   Development: This branch compiles the code and checks that the installation and preparation stages are ready.
#                Used to confirm there are no defects on the compilation code.
#   Testing: This branch activales all unit tests, integration and accceptance tests.
#            After the testing completes suucessfully then the script activated the steps to update the sonarcloud quality gate data.
#
version: 2.1
jobs:
  start-job:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          command: |
            ./gradlew --version

  compile-datamanagement-job:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: DATAMANAGEMENT - Compile the current library code
          working_directory: NeoCom.DataManagement
          command: |
            ../gradlew classes

  test-datamanagement-job:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          _JAVA_OPTIONS: "-Xmx3g"
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - run:
          name: BACKEND - Unit Testing application
          working_directory: NeoCom.DataManagement
          environment:
            PORT: 5140
            JDBC_DATABASE_URL: "jdbc:postgresql://0.0.0.0:5432/postgres"
            DB_USER: inno-user
            DB_PASSWORD: inno-password
          command: |
            ../gradlew test
      - store_test_results:
          path: ~/project/NeoCom.DataManagement/build/test-results
      - store_artifacts:  
          path: ~/project/NeoCom.DataManagement/build/libs

workflows:
  version: 2
  datamanagement-stage:
    jobs:
      - start-job:
          filters:
            branches:
              only:
                - experimental
                - development
                - test

      - compile-datamanagement-job:
          requires:
            - start-job
          filters:
            branches:
              only:
                - experimental
                - development
                - test
      - test-datamanagement-job:
          requires:
            - compile-datamanagement-job
          filters:
            branches:
              only:
                - test
